# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BulkMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BulkMessage.proto',
  package='GiraffeMetering',
  serialized_pb='\n\x11\x42ulkMessage.proto\x12\x0fGiraffeMetering\"\x9f\x01\n\x0b\x42ulkMessage\x12\x11\n\tsignature\x18\x01 \x02(\t\x12\x0f\n\x07host_id\x18\x02 \x02(\t\x12\x31\n\x0chost_records\x18\x03 \x03(\x0b\x32\x1b.GiraffeMetering.HostRecord\x12\x39\n\x10instance_records\x18\x04 \x03(\x0b\x32\x1f.GiraffeMetering.InstanceRecord\"\x8c\x01\n\x0eInstanceRecord\x12\x0f\n\x07user_id\x18\x01 \x02(\t\x12\x12\n\nproject_id\x18\x02 \x02(\t\x12\x13\n\x0binstance_id\x18\x03 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x02(\t\x12\x0c\n\x04type\x18\x05 \x02(\t\x12\r\n\x05value\x18\x06 \x02(\t\x12\x10\n\x08\x64uration\x18\x07 \x02(\x05\"N\n\nHostRecord\x12\x11\n\ttimestamp\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t\x12\x10\n\x08\x64uration\x18\x04 \x02(\x05')




_BULKMESSAGE = _descriptor.Descriptor(
  name='BulkMessage',
  full_name='GiraffeMetering.BulkMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='GiraffeMetering.BulkMessage.signature', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host_id', full_name='GiraffeMetering.BulkMessage.host_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host_records', full_name='GiraffeMetering.BulkMessage.host_records', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_records', full_name='GiraffeMetering.BulkMessage.instance_records', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=198,
)


_INSTANCERECORD = _descriptor.Descriptor(
  name='InstanceRecord',
  full_name='GiraffeMetering.InstanceRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='GiraffeMetering.InstanceRecord.user_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='GiraffeMetering.InstanceRecord.project_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='GiraffeMetering.InstanceRecord.instance_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='GiraffeMetering.InstanceRecord.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='GiraffeMetering.InstanceRecord.type', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='GiraffeMetering.InstanceRecord.value', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='GiraffeMetering.InstanceRecord.duration', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=201,
  serialized_end=341,
)


_HOSTRECORD = _descriptor.Descriptor(
  name='HostRecord',
  full_name='GiraffeMetering.HostRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='GiraffeMetering.HostRecord.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='GiraffeMetering.HostRecord.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='GiraffeMetering.HostRecord.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='GiraffeMetering.HostRecord.duration', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=343,
  serialized_end=421,
)

_BULKMESSAGE.fields_by_name['host_records'].message_type = _HOSTRECORD
_BULKMESSAGE.fields_by_name['instance_records'].message_type = _INSTANCERECORD
DESCRIPTOR.message_types_by_name['BulkMessage'] = _BULKMESSAGE
DESCRIPTOR.message_types_by_name['InstanceRecord'] = _INSTANCERECORD
DESCRIPTOR.message_types_by_name['HostRecord'] = _HOSTRECORD

class BulkMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BULKMESSAGE

  # @@protoc_insertion_point(class_scope:GiraffeMetering.BulkMessage)

class InstanceRecord(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTANCERECORD

  # @@protoc_insertion_point(class_scope:GiraffeMetering.InstanceRecord)

class HostRecord(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOSTRECORD

  # @@protoc_insertion_point(class_scope:GiraffeMetering.HostRecord)


# @@protoc_insertion_point(module_scope)
