# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Message.proto',
  package='GiraffeMetering',
  serialized_pb='\n\rMessage.proto\x12\x0fGiraffeMetering\"\x9a\x01\n\x0cMeterMessage\x12\x11\n\tsignature\x18\x01 \x02(\t\x12\x36\n\x0bhostMessage\x18\x02 \x03(\x0b\x32!.GiraffeMetering.MeterHostMessage\x12?\n\x10instanceMessages\x18\x03 \x03(\x0b\x32%.GiraffeMetering.MeterInstanceMessage\"W\n\x10MeterHostMessage\x12\x0e\n\x06hostID\x18\x01 \x02(\t\x12\x33\n\x06meters\x18\x02 \x03(\x0b\x32#.GiraffeMetering.MeterRecordMessage\"\x82\x01\n\x14MeterInstanceMessage\x12\x12\n\ninstanceID\x18\x01 \x02(\t\x12\x11\n\tprojectID\x18\x02 \x01(\t\x12\x0e\n\x06userID\x18\x03 \x01(\t\x12\x33\n\x06meters\x18\x04 \x03(\x0b\x32#.GiraffeMetering.MeterRecordMessage\"V\n\x12MeterRecordMessage\x12\x11\n\ttimestamp\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t\x12\x10\n\x08\x64uration\x18\x04 \x02(\x05')




_METERMESSAGE = descriptor.Descriptor(
  name='MeterMessage',
  full_name='GiraffeMetering.MeterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='signature', full_name='GiraffeMetering.MeterMessage.signature', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hostMessage', full_name='GiraffeMetering.MeterMessage.hostMessage', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='instanceMessages', full_name='GiraffeMetering.MeterMessage.instanceMessages', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=189,
)


_METERHOSTMESSAGE = descriptor.Descriptor(
  name='MeterHostMessage',
  full_name='GiraffeMetering.MeterHostMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hostID', full_name='GiraffeMetering.MeterHostMessage.hostID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='meters', full_name='GiraffeMetering.MeterHostMessage.meters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=191,
  serialized_end=278,
)


_METERINSTANCEMESSAGE = descriptor.Descriptor(
  name='MeterInstanceMessage',
  full_name='GiraffeMetering.MeterInstanceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='instanceID', full_name='GiraffeMetering.MeterInstanceMessage.instanceID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='projectID', full_name='GiraffeMetering.MeterInstanceMessage.projectID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userID', full_name='GiraffeMetering.MeterInstanceMessage.userID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='meters', full_name='GiraffeMetering.MeterInstanceMessage.meters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=281,
  serialized_end=411,
)


_METERRECORDMESSAGE = descriptor.Descriptor(
  name='MeterRecordMessage',
  full_name='GiraffeMetering.MeterRecordMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='GiraffeMetering.MeterRecordMessage.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='GiraffeMetering.MeterRecordMessage.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='GiraffeMetering.MeterRecordMessage.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='duration', full_name='GiraffeMetering.MeterRecordMessage.duration', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=413,
  serialized_end=499,
)

_METERMESSAGE.fields_by_name['hostMessage'].message_type = _METERHOSTMESSAGE
_METERMESSAGE.fields_by_name['instanceMessages'].message_type = _METERINSTANCEMESSAGE
_METERHOSTMESSAGE.fields_by_name['meters'].message_type = _METERRECORDMESSAGE
_METERINSTANCEMESSAGE.fields_by_name['meters'].message_type = _METERRECORDMESSAGE
DESCRIPTOR.message_types_by_name['MeterMessage'] = _METERMESSAGE
DESCRIPTOR.message_types_by_name['MeterHostMessage'] = _METERHOSTMESSAGE
DESCRIPTOR.message_types_by_name['MeterInstanceMessage'] = _METERINSTANCEMESSAGE
DESCRIPTOR.message_types_by_name['MeterRecordMessage'] = _METERRECORDMESSAGE

class MeterMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METERMESSAGE
  
  # @@protoc_insertion_point(class_scope:GiraffeMetering.MeterMessage)

class MeterHostMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METERHOSTMESSAGE
  
  # @@protoc_insertion_point(class_scope:GiraffeMetering.MeterHostMessage)

class MeterInstanceMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METERINSTANCEMESSAGE
  
  # @@protoc_insertion_point(class_scope:GiraffeMetering.MeterInstanceMessage)

class MeterRecordMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METERRECORDMESSAGE
  
  # @@protoc_insertion_point(class_scope:GiraffeMetering.MeterRecordMessage)

# @@protoc_insertion_point(module_scope)
