# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Message.proto',
  package='GiraffeMetering',
  serialized_pb='\n\rMessage.proto\x12\x0fGiraffeMetering\"L\n\x08\x45nvelope\x12\x11\n\tsignature\x18\x01 \x02(\t\x12-\n\x07message\x18\x02 \x02(\x0b\x32\x1c.GiraffeMetering.BulkMessage\"\x86\x01\n\x0b\x42ulkMessage\x12\x11\n\thost_name\x18\x02 \x02(\t\x12\x31\n\x0chost_records\x18\x03 \x03(\x0b\x32\x1b.GiraffeMetering.HostRecord\x12\x31\n\x0cinst_records\x18\x04 \x03(\x0b\x32\x1b.GiraffeMetering.InstRecord\"\x8a\x01\n\nInstRecord\x12\x0f\n\x07user_id\x18\x01 \x02(\t\x12\x12\n\nproject_id\x18\x02 \x02(\t\x12\x0f\n\x07inst_id\x18\x03 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x02(\t\x12\x12\n\nmeter_name\x18\x05 \x02(\t\x12\r\n\x05value\x18\x06 \x02(\t\x12\x10\n\x08\x64uration\x18\x07 \x02(\x05\"T\n\nHostRecord\x12\x11\n\ttimestamp\x18\x01 \x02(\t\x12\x12\n\nmeter_name\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t\x12\x10\n\x08\x64uration\x18\x04 \x02(\x05')




_ENVELOPE = descriptor.Descriptor(
  name='Envelope',
  full_name='GiraffeMetering.Envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='signature', full_name='GiraffeMetering.Envelope.signature', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='GiraffeMetering.Envelope.message', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=110,
)


_BULKMESSAGE = descriptor.Descriptor(
  name='BulkMessage',
  full_name='GiraffeMetering.BulkMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='host_name', full_name='GiraffeMetering.BulkMessage.host_name', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='host_records', full_name='GiraffeMetering.BulkMessage.host_records', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inst_records', full_name='GiraffeMetering.BulkMessage.inst_records', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=113,
  serialized_end=247,
)


_INSTRECORD = descriptor.Descriptor(
  name='InstRecord',
  full_name='GiraffeMetering.InstRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='GiraffeMetering.InstRecord.user_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='project_id', full_name='GiraffeMetering.InstRecord.project_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inst_id', full_name='GiraffeMetering.InstRecord.inst_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='GiraffeMetering.InstRecord.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='meter_name', full_name='GiraffeMetering.InstRecord.meter_name', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='GiraffeMetering.InstRecord.value', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='duration', full_name='GiraffeMetering.InstRecord.duration', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=250,
  serialized_end=388,
)


_HOSTRECORD = descriptor.Descriptor(
  name='HostRecord',
  full_name='GiraffeMetering.HostRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='GiraffeMetering.HostRecord.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='meter_name', full_name='GiraffeMetering.HostRecord.meter_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='GiraffeMetering.HostRecord.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='duration', full_name='GiraffeMetering.HostRecord.duration', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=390,
  serialized_end=474,
)

_ENVELOPE.fields_by_name['message'].message_type = _BULKMESSAGE
_BULKMESSAGE.fields_by_name['host_records'].message_type = _HOSTRECORD
_BULKMESSAGE.fields_by_name['inst_records'].message_type = _INSTRECORD
DESCRIPTOR.message_types_by_name['Envelope'] = _ENVELOPE
DESCRIPTOR.message_types_by_name['BulkMessage'] = _BULKMESSAGE
DESCRIPTOR.message_types_by_name['InstRecord'] = _INSTRECORD
DESCRIPTOR.message_types_by_name['HostRecord'] = _HOSTRECORD

class Envelope(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENVELOPE
  
  # @@protoc_insertion_point(class_scope:GiraffeMetering.Envelope)

class BulkMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BULKMESSAGE
  
  # @@protoc_insertion_point(class_scope:GiraffeMetering.BulkMessage)

class InstRecord(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTRECORD
  
  # @@protoc_insertion_point(class_scope:GiraffeMetering.InstRecord)

class HostRecord(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOSTRECORD
  
  # @@protoc_insertion_point(class_scope:GiraffeMetering.HostRecord)

# @@protoc_insertion_point(module_scope)
